name: sr
channels:
  - pytorch
  - conda-forge
dependencies:
  - anyio=4.4.0
  - appnope=0.1.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.2.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - bleach=6.1.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.6.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - comm=0.2.2
  - contourpy=1.2.1
  - cycler=0.12.1
  - debugpy=1.8.2
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - filelock=3.15.4
  - fonttools=4.53.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - idna=3.7
  - importlib-metadata=8.0.0
  - importlib_metadata=8.0.0
  - importlib_resources=6.4.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - ipywidgets=8.1.3
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.22.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.22.0
  - jupyter=1.0.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.2
  - jupyterlab_widgets=3.0.11
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=17.0.6
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libopenblas=0.3.24
  - libpng=1.6.43
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libtiff=4.6.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libzlib=1.3.1
  - llvm-openmp=15.0.7
  - markupsafe=2.1.5
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - nbclient=0.10.0
  - nbconvert=7.16.4
  - nbconvert-core=7.16.4
  - nbconvert-pandoc=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.3
  - notebook=7.2.1
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.1
  - overrides=7.7.0
  - packaging=24.1
  - pandas=2.2.2
  - pandoc=3.2.1
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=0.5.6
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.22
  - pygments=2.18.0
  - pyobjc-core=10.3.1
  - pyobjc-framework-cocoa=10.3.1
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.11.9
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytorch=2.3.1
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - qtconsole-base=5.5.2
  - qtpy=2.4.1
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.18.1
  - scikit-learn=1.3.1
  - scipy=1.14.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=70.1.1
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.2
  - statsmodels=0.14.2
  - sympy=1.12.1
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tinycss2=1.3.0
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.4.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024a
  - uri-template=1.3.0
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - webcolors=24.6.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - widgetsnbextension=4.0.11
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.19.2
  - zstandard=0.22.0
  - zstd=1.5.6
